### ISSUE TITLE
Dealing with N/A Values

### ISSUE THREAD

**Issue by Swaijit-Singh** [Swaijit-Singh/AI-ML-hacktoberfest#1]
The Spaceship-Titanic Dataset contains substantial N/A values in both Train and test datasets. Therefore, This issue is created to deal with the same. Go into the [spaceship-titanic](https://github.com/Swaijit-Singh/AI-ML-hacktoberfest/tree/main/spaceship-titanic) directory and you will find the [Space-TItanic-AI-ML-hacktoberfest.ipynb](https://github.com/Swaijit-Singh/AI-ML-hacktoberfest/blob/main/spaceship-titanic/Space-TItanic-AI-ML-hacktoberfest.ipynb) Jupiter notebook. Within the EDA section of the notebook, you will find the Dealing with N/A Values section. That is where you will be making the changes if this issue is assigned to you. If you would like to be assigned this issue comment below.

**Comment by Anway-Agte** [comment]
Hi @Swaijit-Singh I would like to work on this issue as well.
