### ISSUE TITLE
Univariate Analysis

### ISSUE THREAD

**Issue by Swaijit-Singh** [Swaijit-Singh/AI-ML-hacktoberfest#2]
The Spaceship-Titanic Dataset contains Multiple variables in both Train and test datasets. Therefore, This issue is created to assign duties of conducting a Univariate Analysis along with Visualizations of all the Variables present in the dataset. Go into the [spaceship-titanic](https://github.com/Swaijit-Singh/AI-ML-hacktoberfest/tree/main/spaceship-titanic) directory and you will find the [Space-TItanic-AI-ML-hacktoberfest.ipynb](https://github.com/Swaijit-Singh/AI-ML-hacktoberfest/blob/main/spaceship-titanic/Space-TItanic-AI-ML-hacktoberfest.ipynb) Jupiter notebook. Within the Visualization section of the notebook, you will find the Univariate Analysis section. That is where you will be making the changes if this issue is assigned to you. If you would like to be assigned this issue comment below.

**Comment by manaslohani** [comment]
Hi, Kindly assign this issue to me.

**Comment by Bhanuprakash93** [comment]
Hi, I like to do this
